version: '3'

services:
  pwn_monster_3:
    build:
      context: '.'
      args:
        - BINARY_NAME=vuln
    image: 'pwn_monster_3_image'
    container_name: 'pwn_monster_3'
    ports:
      # - '9003:9999/tcp'
      - '127.0.0.1:9003:9999/tcp'
